### ISSUE TITLE
Question: umbraco 8 migration path..

### ISSUE THREAD

**Issue by mistyn8** [Jumoo/uSyncMigrations#94]
I was trying to take a u8 export and migrate into a clean u10 site.

I put the `usync/v8` folder in the clean u10 site and ran the migration in place, selecting the v8 folder.

I'm guessing this isn't an intended pathway, as the dtge migrators didn't create any of the elements that relate to the dtge existing doctypes?

Is the prefered pathway here to update the existing db from v8 to v10, and then migrate in place, before then usync exporting, to import into a clean v10? Or is that just overkill?

**Comment by KevinJump** [comment]
Hi, 

yeah we need to clean up the UI path , because you are not the only one to see this - 

Umbraco 8 -> 10 .  does not require migration of the usync files.

you can pick up a uSync/v8 folder and copy it to uSync/v9 inside an Umbraco 9/10/11 site and then run the import and you will get all of your site/settings in Umbraco 10.

if you want to go from say NestedContent to BlockList or Grid to BlockGrid then you can run a 'Conversion' on your v10 site and uSync.Migrations will attempt to migrate the properties from one to another. 

but v8 on its own 'just' copy the files. 

---

- [ ] I am thinking we might change up the UI. so it starts with something like  "what version are you coming from?" then guides you down the right path.

**Comment by mistyn8** [comment]
Thanks, I'll try that.

**Comment by KevinJump** [comment]
Closing - we've added a note in the latest beta, to help people see this. #104
