### ISSUE TITLE
Content Picker being set to be an integer

### ISSUE THREAD

**Issue by drpeck** [Jumoo/uSyncMigrations#95]
My content picker v7 usync file looks like this:

```
<?xml version="1.0" encoding="utf-8"?>
<DataType Name="Content Picker" Key="a6857c73-d6e9-480c-b6e6-f15f6ad11125" Id="Umbraco.ContentPickerAlias" DatabaseType="Integer">
  <PreValues />
</DataType>
```

That changes the data type of a content picker to be an Integer, which breaks the picker going forward (needs to support JSON). Happy to try to debug and submit a PR, but not sure what the best approach is.

Maybe [this commit](https://github.com/Jumoo/uSyncMigrations/commit/8efe3b575c432309a74066f5d0ccb29ff234b419) will fix it already?

**Comment by KevinJump** [comment]
Yeah - double check you are running the very latest release, that might fix it. 

I suspect you need to extend the content picker migrator ( https://github.com/Jumoo/uSyncMigrations/blob/main/uSync.Migrations/Migrators/Core/ContentPickerMigrator.cs )

to add a `GetContentValue` method that will return the proper 'Udi value strings' 

if you current content picker is storing Int values, then you will need to convert them to Uid strings

its been a **suupper long time since i looked** - but if you take a look inside the v7 config file, it should contain something that you can hopefully use to map from the id value to a UID value.

**Comment by drpeck** [comment]
Oh nuts. I'm only partly stupid. I did go to check that I was running the latest version, but forgot to 'include pre-release'. That resolves this issue.

I've still got an issue where a guid is saved instead of a UUID, so the rest of your response is helpful. 

I'm guessing that `SyncMigrationContext.GetKey()` is used for mapping an int Id to a Key, is that right?
